name: Python CI

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      id: tests
      run: python src/test.py
      
    - name: Check test results
      if: steps.tests.outcome == 'failure'
      run: |
        echo "Tests failed. Exiting workflow."
        exit 1

    - name: List directory contents
      run: ls -al

    - name: Run build.py
      run: python build.py
      
    - name: List directory contents
      run: ls -al
    
    - name: Check for new files # check if 2 new files were created after running build.py  
      run: |
        NEW_FILES_COUNT=$(git status --porcelain | grep "^??" | wc -l)
        if [ "$NEW_FILES_COUNT" -ne 2 ]; then
          echo "Expected 2 new files but found $NEW_FILES_COUNT"
          exit 1
        fi

